# Security Hardening & Compliance Configuration
# Ultimate Arbitrage System

sast:
  enabled: true
  tools:
    - semgrep
    - bandit
    - safety
    - pylint
  rules_path: "./security/rules"
  exclude_paths:
    - "node_modules"
    - ".git"
    - "__pycache__"
    - "*.pyc"
    - "venv"
    - ".env"
  severity_threshold: "medium"
  fail_on_critical: true

dast:
  enabled: true
  tools:
    - owasp-zap
    - nuclei
    - nmap
  target_urls:
    - "http://localhost:8000"
    - "http://localhost:3000"
  authentication:
    type: "basic"
    username: "admin"
    password_env: "DAST_PASSWORD"
  max_scan_duration: 1800  # 30 minutes
  aggressive_mode: false

dependency_scanning:
  enabled: true
  tools:
    - osv-scanner
    - trivy
    - safety
    - snyk
  package_managers:
    - pip
    - npm
    - go
    - cargo
    - maven
  vulnerability_database_update: true
  ignore_dev_dependencies: false
  severity_threshold: "medium"

container_hardening:
  enabled: true
  distroless: true
  rootless: true
  seccomp: true
  apparmor: true
  read_only_root: true
  no_new_privileges: true
  user_namespace: true
  cgroup_limits:
    memory: "512m"
    cpu: "0.5"
  network_policies:
    - deny_all_ingress
    - allow_specific_egress

compliance:
  frameworks:
    - soc2
    - iso27001
    - gdpr
    - nist
  jira_integration:
    enabled: false
    url: "https://your-company.atlassian.net"
    username: "compliance@company.com"
    api_token_env: "JIRA_API_TOKEN"
    project_key: "COMPLIANCE"
  evidence_storage:
    path: "./compliance/evidence"
    retention_years: 7
  policy_documents:
    path: "./compliance/policies"
    review_frequency: "annual"

audit:
  penetration_testing:
    enabled: true
    frequency: "quarterly"
    external_vendor: "CyberSec Pro"
    scope:
      - web_applications
      - apis
      - infrastructure
      - social_engineering
    reporting:
      format: "pdf"
      confidentiality: "restricted"
  
  aml_cft_screening:
    enabled: true
    ofac_api_key_env: "OFAC_API_KEY"
    frequency: "daily"
    batch_processing: true
    sanctions_lists:
      - ofac_sdn
      - un_consolidated
      - eu_consolidated
      - hmt_consolidated
      - dfat_consolidated
    risk_scoring:
      high_risk_countries:
        - "IR"  # Iran
        - "KP"  # North Korea
        - "SY"  # Syria
      suspicious_patterns:
        - large_round_amounts
        - unusual_trading_hours
        - rapid_fund_movements
        - shell_company_indicators
    
  vulnerability_management:
    enabled: true
    scan_frequency: "weekly"
    patch_management:
      critical_patch_sla: 24  # hours
      high_patch_sla: 72     # hours
      medium_patch_sla: 168  # hours (1 week)
    
  incident_response:
    enabled: true
    team_contacts:
      - "security@company.com"
      - "ciso@company.com"
    escalation_matrix:
      low: "security_analyst"
      medium: "security_manager"
      high: "ciso"
      critical: "ceo"

encryption:
  data_at_rest:
    algorithm: "AES-256-GCM"
    key_management: "AWS KMS"
    key_rotation: "quarterly"
  
  data_in_transit:
    tls_version: "1.3"
    cipher_suites:
      - "TLS_AES_256_GCM_SHA384"
      - "TLS_CHACHA20_POLY1305_SHA256"
    certificate_management: "Let's Encrypt"
  
  key_management:
    hsm_enabled: true
    key_escrow: true
    backup_encryption: true

monitoring:
  security_events:
    siem_enabled: true
    log_aggregation: "ELK Stack"
    real_time_alerts: true
    retention_days: 365
  
  metrics:
    security_kpis:
      - mean_time_to_detection
      - mean_time_to_response
      - vulnerability_remediation_rate
      - security_training_completion
    
  alerting:
    channels:
      - email
      - slack
      - pagerduty
    severity_routing:
      critical: "pagerduty"
      high: "slack"
      medium: "email"

third_party_risk:
  vendor_assessment:
    security_questionnaire: true
    penetration_test_reports: true
    compliance_certifications: true
    ongoing_monitoring: true
  
  api_security:
    rate_limiting: true
    api_gateway: true
    oauth2_scopes: true
    jwt_validation: true

business_continuity:
  backup_strategy:
    frequency: "daily"
    retention: "1year"
    offsite_storage: true
    encryption: true
    testing_frequency: "monthly"
  
  disaster_recovery:
    rpo: "1hour"  # Recovery Point Objective
    rto: "4hours" # Recovery Time Objective
    hot_site: true
    failover_testing: "quarterly"

privacy:
  data_minimization:
    enabled: true
    data_classification: true
    retention_policies: true
    automated_deletion: true
  
  consent_management:
    enabled: true
    granular_consent: true
    consent_withdrawal: true
    audit_trail: true
  
  data_subject_rights:
    access_request: true
    portability: true
    rectification: true
    erasure: true
    automated_processing_opt_out: true

training:
  security_awareness:
    frequency: "quarterly"
    phishing_simulation: true
    compliance_training: true
    role_based_training: true
  
  certification_requirements:
    security_team:
      - "CISSP"
      - "CISM"
      - "CEH"
    developers:
      - "Secure Coding"
      - "OWASP Top 10"
    executives:
      - "Cybersecurity Leadership"

reporting:
  frequency: "monthly"
  stakeholders:
    - "CISO"
    - "CTO"
    - "Board of Directors"
    - "Audit Committee"
  
  metrics:
    - security_posture_score
    - compliance_status
    - vulnerability_metrics
    - incident_statistics
    - training_completion_rates

budget:
  annual_security_budget: 500000
  allocation:
    tools_and_technology: 40
    personnel: 35
    training_and_certification: 10
    external_services: 10
    contingency: 5

