# Ultimate Arbitrage System - Advanced Configuration
# ==============================================
# This configuration enables the system's fullest potential with:
# - Quantum computing integration
# - Advanced AI strategies
# - Real-time market data
# - Multi-asset class support
# - Risk management optimization
# - Performance maximization

# System Metadata
system:
  name: "Ultimate Arbitrage System"
  version: "2.0.0"
  environment: "production"  # development, staging, production
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  max_threads: 16
  enable_gpu: true
  enable_quantum: true
  enable_distributed: true

# Core Engine Configuration
core:
  optimization_engine: "ultra_advanced"  # basic, advanced, ultra_advanced
  use_quantum_computing: true
  quantum_advantage_threshold: 1.1
  continuous_learning: true
  real_time_optimization: true
  auto_model_selection: true
  performance_target_sharpe: 3.0
  max_drawdown_limit: 0.05  # 5%
  confidence_threshold: 0.8

# Quantum Computing Settings
quantum:
  provider: "qiskit"  # qiskit, cirq, rigetti
  backend: "aer_simulator"  # Local simulator
  # backend: "ibmq_qasm_simulator"  # IBM Quantum
  shots: 1024
  optimization_level: 3
  noise_model: false
  error_mitigation: true
  circuit_depth: 5
  enable_vqe: true
  enable_qaoa: true
  
# Advanced AI Configuration
ai:
  ensemble_weights:
    transformer: 0.35
    gnn: 0.25
    reinforcement_learning: 0.20
    meta_learning: 0.20
  
  models:
    transformer:
      model_type: "GPT4Finance"
      hidden_size: 512
      num_layers: 12
      attention_heads: 8
      dropout: 0.1
      learning_rate: 0.0001
      batch_size: 32
      
    gnn:
      model_type: "GraphTransformer"
      hidden_channels: 256
      num_layers: 6
      heads: 8
      dropout: 0.1
      learning_rate: 0.001
      
    reinforcement_learning:
      algorithm: "PPO"  # PPO, SAC, TD3
      policy_network:
        hidden_sizes: [256, 256, 128]
        activation: "relu"
      value_network:
        hidden_sizes: [256, 256]
        activation: "relu"
      learning_rate: 0.0003
      gamma: 0.99
      clip_ratio: 0.2
      
    meta_learning:
      algorithm: "MAML"  # MAML, Reptile
      inner_lr: 0.01
      outer_lr: 0.001
      num_inner_updates: 5
      
  training:
    enable_online_learning: true
    adaptation_frequency: 100  # steps
    retraining_frequency: 1000  # steps
    validation_split: 0.2
    early_stopping_patience: 50
    
# Market Data Configuration
data:
  sources:
    yahoo_finance:
      enabled: true
      priority: 2
      rate_limit: 60  # requests per minute
      cache_ttl: 300  # seconds
      
    alpha_vantage:
      enabled: false  # Set to true with API key
      api_key: "YOUR_ALPHA_VANTAGE_KEY"
      priority: 3
      rate_limit: 5
      cache_ttl: 300
      
    polygon:
      enabled: false  # Set to true with API key
      api_key: "YOUR_POLYGON_KEY"
      priority: 4
      rate_limit: 200
      cache_ttl: 60
      
    iex_cloud:
      enabled: false  # Set to true with API key
      api_key: "YOUR_IEX_KEY"
      priority: 3
      rate_limit: 100
      cache_ttl: 300
      
  real_time:
    enabled: true
    update_frequency: 5  # seconds
    websocket_enabled: true
    data_quality_threshold: 3  # 1-5 scale
    
  caching:
    enabled: true
    backend: "redis"  # redis, memory, file
    redis:
      host: "localhost"
      port: 6379
      db: 0
      password: null
      ttl: 300
      
# Trading Configuration
trading:
  mode: "paper"  # paper, live
  
  brokers:
    alpaca:
      enabled: false  # Set to true for live trading
      api_key: "YOUR_ALPACA_KEY"
      secret_key: "YOUR_ALPACA_SECRET"
      base_url: "https://paper-api.alpaca.markets"  # Paper trading
      # base_url: "https://api.alpaca.markets"  # Live trading
      
    interactive_brokers:
      enabled: false
      host: "127.0.0.1"
      port: 7497  # Paper: 7497, Live: 7496
      client_id: 1
      
  execution:
    algorithm: "smart"  # market, limit, smart, twap, vwap
    max_order_size: 10000  # USD
    min_order_size: 100   # USD
    slippage_tolerance: 0.001  # 0.1%
    commission_per_share: 0.005  # $0.005 per share
    
  risk_management:
    max_position_size: 0.2  # 20% of portfolio
    max_portfolio_exposure: 1.0  # 100% - can use leverage
    stop_loss_threshold: 0.05  # 5%
    take_profit_threshold: 0.15  # 15%
    max_correlation: 0.7
    
# Strategy Marketplace Configuration
strategies:
  enabled_strategies:
    - "quantum_momentum"
    - "adaptive_momentum" 
    - "cross_asset_momentum"
    - "ai_mean_reversion"
    - "volatility_targeting"
    - "statistical_arbitrage"
    - "deep_rl"
    
  strategy_configs:
    quantum_momentum:
      enabled: true
      allocation: 0.25  # 25% of portfolio
      use_quantum: true
      quantum_depth: 3
      momentum_threshold: 0.02
      volatility_adjustment: true
      max_momentum_exposure: 0.3
      
    adaptive_momentum:
      enabled: true
      allocation: 0.20
      adaptation_frequency: 20
      use_neural_net: true
      timeframes: ["5min", "1h", "1d"]
      timeframe_weights: [0.2, 0.3, 0.5]
      min_confidence_threshold: 0.6
      
    cross_asset_momentum:
      enabled: true
      allocation: 0.15
      asset_classes:
        equity: ["SPY", "QQQ", "IWM", "EFA", "EEM"]
        bond: ["TLT", "IEF", "SHY", "HYG", "EMB"]
        commodity: ["GLD", "SLV", "DBA", "USO", "UNG"]
        crypto: ["BTC-USD", "ETH-USD", "ADA-USD"]
        forex: ["UUP", "FXE", "FXY", "FXC"]
      top_n_assets: 5
      rebalance_frequency: 5  # days
      diversification_bonus: 0.1
      
    ai_mean_reversion:
      enabled: true
      allocation: 0.15
      lookback_window: 20
      z_score_threshold: 2.0
      half_life: 10
      use_machine_learning: true
      
    volatility_targeting:
      enabled: true
      allocation: 0.10
      target_volatility: 0.15  # 15% annualized
      volatility_window: 30
      rebalance_threshold: 0.02
      
    statistical_arbitrage:
      enabled: true
      allocation: 0.10
      pairs_selection_method: "cointegration"
      lookback_period: 252
      entry_threshold: 2.0
      exit_threshold: 0.5
      
    deep_rl:
      enabled: true
      allocation: 0.05
      algorithm: "PPO"
      observation_window: 50
      action_space: "continuous"
      reward_function: "sharpe_ratio"
      
# Risk Management Configuration
risk:
  portfolio_level:
    max_volatility: 0.15  # 15% annualized
    max_drawdown: 0.05    # 5%
    var_confidence: 0.95  # 95% VaR
    stress_test_scenarios: 10
    
  position_level:
    max_weight: 0.2       # 20% per position
    max_sector_weight: 0.4  # 40% per sector
    max_correlation: 0.7  # Maximum correlation between positions
    
  dynamic_hedging:
    enabled: true
    hedge_ratio_target: 0.5
    rebalance_frequency: "daily"
    instruments: ["VIX", "TLT", "GLD"]
    
  stress_testing:
    enabled: true
    scenarios:
      - name: "2008_crisis"
        equity_shock: -0.4
        bond_rally: 0.15
        volatility_spike: 3.0
      - name: "covid_crash"
        equity_shock: -0.35
        volatility_spike: 4.0
        credit_spread: 0.5
      - name: "inflation_shock"
        bond_sell_off: -0.2
        commodity_rally: 0.3
        currency_debasement: -0.1
        
# Performance Attribution
performance:
  benchmarks:
    - symbol: "SPY"
      name: "S&P 500"
      weight: 0.6
    - symbol: "QQQ"
      name: "NASDAQ 100"
      weight: 0.4
      
  attribution_factors:
    - "market_beta"
    - "size_factor"
    - "value_factor"
    - "momentum_factor"
    - "quality_factor"
    - "volatility_factor"
    
  reporting:
    frequency: "daily"
    include_intraday: true
    risk_decomposition: true
    factor_attribution: true
    
# Monitoring and Alerting
monitoring:
  enabled: true
  
  metrics:
    portfolio_value: true
    daily_pnl: true
    sharpe_ratio: true
    max_drawdown: true
    volatility: true
    var_95: true
    
  alerts:
    email:
      enabled: false
      smtp_server: "smtp.gmail.com"
      smtp_port: 587
      username: "your_email@gmail.com"
      password: "your_app_password"
      recipients: ["alerts@yourcompany.com"]
      
    slack:
      enabled: false
      webhook_url: "YOUR_SLACK_WEBHOOK_URL"
      channel: "#trading-alerts"
      
    discord:
      enabled: false
      webhook_url: "YOUR_DISCORD_WEBHOOK_URL"
      
  thresholds:
    daily_loss_limit: -0.02  # -2% daily loss
    drawdown_alert: -0.03    # -3% drawdown alert
    volatility_alert: 0.25   # 25% volatility alert
    
# Database Configuration
database:
  type: "postgresql"  # postgresql, mysql, sqlite
  
  postgresql:
    host: "localhost"
    port: 5432
    database: "ultimate_arbitrage"
    username: "trader"
    password: "secure_password"
    pool_size: 20
    max_overflow: 30
    
  backup:
    enabled: true
    frequency: "daily"
    retention_days: 30
    location: "./backups/"
    
# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  
  authentication:
    enabled: true
    secret_key: "your_super_secret_key_change_this"
    algorithm: "HS256"
    access_token_expire_minutes: 30
    
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
    
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "https://yourdomain.com"
      
# UI Configuration
ui:
  frontend:
    port: 3000
    api_url: "http://localhost:8000"
    websocket_url: "ws://localhost:8000/ws"
    
  theme:
    primary_color: "#1976d2"
    secondary_color: "#dc004e"
    dark_mode: true
    
  features:
    real_time_charts: true
    advanced_analytics: true
    strategy_builder: true
    backtesting: true
    paper_trading: true
    
# Backtesting Configuration
backtesting:
  default_start_date: "2020-01-01"
  default_end_date: "2023-12-31"
  initial_capital: 1000000  # $1M
  benchmark: "SPY"
  
  settings:
    commission: 0.005  # $0.005 per share
    slippage: 0.001    # 0.1%
    market_impact: 0.0005  # 0.05%
    
  performance_metrics:
    - "total_return"
    - "annualized_return"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "calmar_ratio"
    - "max_drawdown"
    - "volatility"
    - "var_95"
    - "beta"
    - "alpha"
    - "tracking_error"
    
# Integration Settings
integration:
  data_refresh_interval: 300  # seconds
  ai_ensemble_weights:
    transformer: 0.35
    gnn: 0.25
    rl: 0.20
    meta: 0.20
  auto_model_selection: true
  continuous_learning: true
  real_time_data: true
  news_sentiment_weight: 0.1
  social_sentiment_weight: 0.05
  max_position_size: 0.2
  max_portfolio_volatility: 0.15
  drawdown_limit: 0.1
  var_confidence: 0.95
  rebalancing_frequency: "daily"
  optimization_horizon: 30
  backtesting_period: 252
  benchmark_indices: ["SPY", "QQQ", "IWM", "EFA", "EEM"]
  performance_attribution: true
  risk_attribution: true
  automation_level: "full"
  human_oversight: false
  confidence_threshold: 0.8

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  handlers:
    console:
      enabled: true
      level: "INFO"
      
    file:
      enabled: true
      level: "DEBUG"
      filename: "logs/system.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5
      
    rotating:
      enabled: true
      level: "INFO"
      filename: "logs/trading.log"
      when: "midnight"
      interval: 1
      backup_count: 30
      
# Security Configuration
security:
  encryption:
    enabled: true
    algorithm: "AES-256"
    
  api_keys:
    encryption_enabled: true
    rotation_days: 90
    
  audit_logging:
    enabled: true
    log_all_trades: true
    log_strategy_changes: true
    log_risk_breaches: true
    
# Development Settings
development:
  debug_mode: false
  profiling_enabled: false
  
  testing:
    run_unit_tests: true
    run_integration_tests: true
    performance_benchmarks: true
    
  mock_data:
    enabled: false  # Use real market data
    symbols: ["AAPL", "GOOGL", "MSFT", "AMZN", "TSLA"]
    
# Advanced Features
advanced:
  multi_threading: true
  gpu_acceleration: true
  distributed_computing: false
  
  optimization:
    jit_compilation: true
    vectorization: true
    memory_optimization: true
    
  experimental:
    quantum_ml: true
    neuromorphic_computing: false
    optical_computing: false

