# Ultimate Master Orchestrator Configuration
# ==========================================
# Advanced configuration for the central coordination engine

# Core Orchestrator Settings
orchestrator:
  version: "1.0.0"
  max_concurrent_executions: 50
  cycle_frequency_ms: 10  # 100 cycles per second for maximum responsiveness
  enable_advanced_logging: true
  performance_mode: "ultra_high"  # Options: normal, high, ultra_high
  zero_human_intervention: true

# Signal Fusion Engine Configuration
signal_fusion:
  consensus_threshold: 0.75  # 75% consensus required for execution
  signal_weights:
    arbitrage: 0.35      # Highest weight - most reliable
    momentum: 0.25       # Strong trend signals
    mean_reversion: 0.20 # Counter-trend opportunities
    volatility: 0.10     # Volatility-based strategies
    sentiment: 0.05      # Market sentiment
    news: 0.03           # News-based signals
    whale: 0.02          # Large trader movements
    mev: 0.00           # MEV opportunities (disabled initially)
  
  max_signal_age_seconds: 30
  fusion_timeout_ms: 50
  enable_ai_consensus: true
  confidence_boost_factor: 1.2

# Performance Optimization Configuration
performance:
  optimization_interval_seconds: 60
  enable_dynamic_scaling: true
  auto_tuning: true
  
  # Resource Thresholds
  thresholds:
    cpu_warning: 70.0
    cpu_critical: 85.0
    memory_warning: 75.0
    memory_critical: 90.0
    latency_warning_ms: 100
    latency_critical_ms: 500
    error_rate_warning: 0.02
    error_rate_critical: 0.10
  
  # Optimization Strategies
  strategies:
    enable_concurrent_task_reduction: true
    enable_cache_optimization: true
    enable_database_query_optimization: true
    enable_polling_frequency_adjustment: true
    enable_performance_mode_switching: true

# Health Monitoring Configuration
health:
  monitoring_interval_seconds: 10
  health_check_timeout_ms: 5000
  consecutive_failure_threshold: 3
  enable_predictive_analysis: true
  enable_auto_recovery: true
  
  # Alert Thresholds
  alerts:
    cpu_warning: 70.0
    memory_warning: 75.0
    latency_warning_ms: 100
    error_rate_warning: 0.02
    uptime_critical_percentage: 99.0
  
  # Recovery Actions
  recovery:
    enable_component_restart: true
    enable_failover: true
    max_recovery_attempts: 3
    recovery_cooldown_seconds: 300

# Execution Coordination Configuration
execution:
  max_concurrent_executions: 50
  execution_timeout_ms: 30000
  priority_queue_size: 1000
  enable_microsecond_precision: true
  
  # Execution Priorities
  priority_weights:
    critical: 1
    high: 2
    medium: 3
    low: 4
    background: 5
  
  # Risk Management
  risk:
    max_position_size_percentage: 10.0
    max_daily_loss_percentage: 5.0
    enable_dynamic_position_sizing: true
    risk_score_threshold: 0.8

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  enable_file_logging: true
  log_file_path: "logs/orchestrator.log"
  max_log_file_size_mb: 100
  backup_count: 5
  enable_structured_logging: true
  
  # Component Logging
  components:
    signal_fusion: "DEBUG"
    performance_optimizer: "INFO"
    health_monitor: "INFO"
    execution_coordinator: "DEBUG"

# Database Configuration
database:
  enable_metrics_storage: true
  metrics_retention_days: 30
  enable_signal_history: true
  signal_history_retention_days: 7
  enable_performance_analytics: true
  
  # Connection Settings
  connection:
    pool_size: 10
    max_overflow: 20
    pool_timeout_seconds: 30
    pool_recycle_seconds: 3600

# Redis Configuration for High-Speed Caching
redis:
  enable_caching: true
  host: "localhost"
  port: 6379
  db: 0
  password: null
  
  # Cache Settings
  cache:
    signal_cache_ttl_seconds: 300
    health_cache_ttl_seconds: 60
    performance_cache_ttl_seconds: 180
    enable_compression: true

# Security Configuration
security:
  enable_encryption: true
  encryption_key_rotation_hours: 24
  enable_audit_logging: true
  max_failed_attempts: 5
  lockout_duration_minutes: 30
  
  # API Security
  api:
    enable_rate_limiting: true
    requests_per_minute: 1000
    enable_authentication: true
    token_expiry_hours: 24

# Monitoring and Alerting
monitoring:
  enable_real_time_monitoring: true
  dashboard_update_interval_seconds: 5
  enable_prometheus_metrics: true
  enable_grafana_integration: true
  
  # Alert Channels
  alerts:
    enable_email: true
    enable_slack: true
    enable_webhook: true
    critical_alert_immediate: true

# Development and Testing
development:
  enable_debug_mode: false
  enable_simulation_mode: false
  simulation_speed_multiplier: 1.0
  enable_profiling: false
  enable_memory_monitoring: true

