# Ultra-Advanced Portfolio Optimization Configuration
# ================================================
# Configuration for quantum computing, AI, and advanced optimization features

# System Settings
system:
  name: "UltimateArbitrageSystem-QuantumAI"
  version: "2.0.0"
  environment: "production"  # development, testing, production
  debug_mode: false
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  max_workers: 8
  enable_monitoring: true

# Quantum Computing Configuration
quantum:
  enabled: true
  providers:
    ibm:
      enabled: true
      token: "${IBM_QUANTUM_TOKEN}"  # Set in environment variables
      backend: "ibmq_qasm_simulator"  # or specific quantum device
      use_real_hardware: false  # Set to true for real quantum computers
      max_qubits: 20
      shots: 1024
      optimization_level: 2
    dwave:
      enabled: true
      token: "${DWAVE_TOKEN}"  # Set in environment variables
      solver: "hybrid"  # hybrid, quantum_annealer
      num_reads: 1000
      chain_strength: 1.0
  
  # Quantum Optimization Settings
  optimization:
    quantum_advantage_threshold: 1.1
    noise_mitigation: true
    error_correction: true
    algorithm_preference: "auto"  # qaoa, vqe, annealing, auto
    fallback_classical: true

# AI/ML Configuration
ai:
  enabled: true
  
  # Model Architecture
  models:
    transformer:
      enabled: true
      hidden_dim: 256
      num_layers: 4
      attention_heads: 8
      sequence_length: 60
      embedding_dim: 128
      dropout_rate: 0.2
    
    gnn:
      enabled: true
      hidden_dim: 256
      num_layers: 3
      attention_heads: 4
      correlation_threshold: 0.3
    
    reinforcement_learning:
      enabled: true
      algorithm: "dqn"  # dqn, ppo, a3c
      epsilon_decay: 0.995
      gamma: 0.95
      memory_size: 10000
    
    meta_learning:
      enabled: true
      adaptation_steps: 5
      meta_learning_rate: 0.001
  
  # Training Configuration
  training:
    learning_rate: 0.001
    batch_size: 64
    epochs: 1000
    early_stopping_patience: 50
    l2_regularization: 0.001
    gradient_clip_norm: 1.0
    validation_split: 0.2
    
  # Ensemble Settings
  ensemble:
    enabled: true
    weights:
      transformer: 0.35
      gnn: 0.25
      rl: 0.20
      meta: 0.20
    auto_weight_adjustment: true
    consensus_threshold: 0.7

# Integration Engine Configuration
integration:
  # Core Settings
  automation_level: "full"  # conservative, moderate, aggressive, full
  human_oversight: false
  confidence_threshold: 0.8
  
  # Data Sources
  data_sources:
    - "yahoo_finance"
    - "alpha_vantage"
    - "quandl"
    - "fred_economic_data"
    - "news_api"
    - "twitter_sentiment"
  
  real_time_data: true
  data_refresh_interval: 300  # seconds
  
  # Sentiment Analysis
  sentiment:
    news_weight: 0.1
    social_weight: 0.05
    fundamental_weight: 0.15
    technical_weight: 0.7
  
  # Market Regime Detection
  regime_detection:
    enabled: true
    lookback_period: 252  # trading days
    regime_types:
      - "bull"
      - "bear"
      - "sideways"
      - "volatile"
      - "low_vol"
    confidence_threshold: 0.6

# Portfolio Optimization Settings
portfolio:
  # Core Parameters
  default_risk_tolerance: 0.5
  optimization_horizon: 30  # days
  rebalancing_frequency: "daily"  # hourly, daily, weekly
  
  # Asset Universe
  asset_universe:
    stocks:
      - "AAPL"
      - "GOOGL"
      - "MSFT"
      - "TSLA"
      - "NVDA"
      - "AMZN"
      - "META"
      - "NFLX"
    etfs:
      - "SPY"
      - "QQQ"
      - "IWM"
      - "EFA"
      - "EEM"
    crypto:
      - "BTC-USD"
      - "ETH-USD"
      - "ADA-USD"
  
  # Constraints
  constraints:
    max_position_size: 0.2
    min_position_size: 0.01
    max_portfolio_volatility: 0.15
    max_concentration: 0.5
    sector_limits:
      technology: 0.4
      healthcare: 0.3
      financials: 0.3
      energy: 0.2
  
  # Benchmark Indices
  benchmarks:
    - "SPY"  # S&P 500
    - "QQQ"  # Nasdaq
    - "IWM"  # Russell 2000
    - "EFA"  # Developed Markets
    - "EEM"  # Emerging Markets

# Risk Management Configuration
risk:
  # Risk Limits
  max_drawdown: 0.1
  var_confidence: 0.95
  cvar_confidence: 0.95
  stress_test_scenarios: 100
  
  # Position Limits
  position_limits:
    single_asset: 0.2
    sector: 0.4
    country: 0.5
    currency: 0.6
  
  # Risk Monitoring
  monitoring:
    real_time: true
    alert_thresholds:
      volatility: 0.2
      correlation: 0.8
      drawdown: 0.05
      concentration: 0.3
  
  # Risk Models
  models:
    factor_model: "fama_french_5"
    correlation_model: "exponential_weighted"
    volatility_model: "garch"

# Execution Configuration
execution:
  # Trading Settings
  trading:
    execution_algorithm: "twap"  # twap, vwap, implementation_shortfall
    max_participation_rate: 0.1
    max_order_size: 100000  # USD
    min_order_size: 100     # USD
  
  # Exchanges and Brokers
  exchanges:
    - "NYSE"
    - "NASDAQ"
    - "BATS"
  
  brokers:
    primary: "interactive_brokers"
    backup: "alpaca"
  
  # Order Management
  orders:
    default_order_type: "limit"
    timeout: 300  # seconds
    retry_attempts: 3
    slippage_tolerance: 0.001  # 10 bps

# Performance Analytics
performance:
  # Metrics Calculation
  metrics:
    - "total_return"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "calmar_ratio"
    - "max_drawdown"
    - "volatility"
    - "alpha"
    - "beta"
    - "information_ratio"
  
  # Attribution Analysis
  attribution:
    enabled: true
    factors:
      - "market"
      - "size"
      - "value"
      - "momentum"
      - "quality"
      - "volatility"
  
  # Reporting
  reporting:
    frequency: "daily"
    formats:
      - "json"
      - "csv"
      - "pdf"
    include_charts: true

# API Configuration
api:
  # External APIs
  providers:
    yahoo_finance:
      enabled: true
      rate_limit: 2000  # requests per hour
    
    alpha_vantage:
      enabled: false
      api_key: "${ALPHA_VANTAGE_KEY}"
      rate_limit: 500
    
    quandl:
      enabled: false
      api_key: "${QUANDL_KEY}"
      rate_limit: 300
    
    news_api:
      enabled: false
      api_key: "${NEWS_API_KEY}"
      rate_limit: 1000
  
  # Internal API
  server:
    host: "localhost"
    port: 8000
    workers: 4
    enable_docs: true
    cors_enabled: true

# Database Configuration
database:
  # Primary Database
  primary:
    type: "postgresql"
    host: "localhost"
    port: 5432
    database: "arbitrage_system"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    pool_size: 10
  
  # Cache Database
  cache:
    type: "redis"
    host: "localhost"
    port: 6379
    database: 0
    password: "${REDIS_PASSWORD}"
  
  # Time Series Database
  timeseries:
    type: "influxdb"
    host: "localhost"
    port: 8086
    database: "market_data"
    username: "${INFLUX_USERNAME}"
    password: "${INFLUX_PASSWORD}"

# Monitoring and Logging
monitoring:
  # System Monitoring
  system:
    enabled: true
    metrics_interval: 60  # seconds
    health_check_interval: 30
  
  # Performance Monitoring
  performance:
    enabled: true
    track_latency: true
    track_throughput: true
    track_errors: true
  
  # Alerting
  alerts:
    enabled: true
    channels:
      - "email"
      - "slack"
      - "webhook"
    thresholds:
      cpu_usage: 80
      memory_usage: 85
      disk_usage: 90
      error_rate: 0.05

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Log Files
  files:
    main: "logs/main.log"
    quantum: "logs/quantum.log"
    ai: "logs/ai.log"
    trading: "logs/trading.log"
    risk: "logs/risk.log"
  
  # Rotation
  rotation:
    max_size: "100MB"
    backup_count: 10
    when: "midnight"

# Security Configuration
security:
  # API Security
  api:
    enable_authentication: true
    jwt_secret: "${JWT_SECRET}"
    token_expiry: 3600  # seconds
  
  # Encryption
  encryption:
    algorithm: "AES-256-GCM"
    key: "${ENCRYPTION_KEY}"
  
  # Rate Limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_limit: 150

# Environment Variables Template
# ============================
# Copy to .env file and set your actual values:
#
# # Quantum Computing
# IBM_QUANTUM_TOKEN=your_ibm_quantum_token_here
# DWAVE_TOKEN=your_dwave_token_here
#
# # Market Data APIs
# ALPHA_VANTAGE_KEY=your_alpha_vantage_key_here
# QUANDL_KEY=your_quandl_key_here
# NEWS_API_KEY=your_news_api_key_here
#
# # Database
# DB_USERNAME=your_db_username
# DB_PASSWORD=your_db_password
# REDIS_PASSWORD=your_redis_password
# INFLUX_USERNAME=your_influx_username
# INFLUX_PASSWORD=your_influx_password
#
# # Security
# JWT_SECRET=your_jwt_secret_here
# ENCRYPTION_KEY=your_encryption_key_here

